version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: twilio
    versions:
    - 3.51.0
    - 3.56.0
    - 3.57.0
    - 3.58.0
    - 3.59.0
    - 3.60.0
